name: Telegram Journal Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes

jobs:
  bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: pip install python-telegram-bot
        
      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if journal.json exists and create it if it doesn't
          if [ ! -f "journal.json" ]; then
            echo '{"entries": []}' > journal.json
          fi
          
          # Add and commit changes
          git add journal.json
          
          # Try to commit and handle errors
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update journal entries [skip ci]"
            git push
          fi